### ISSUE TITLE
Packets not coming through

### ISSUE THREAD

**Issue by eliorc** [MonkeySeatRacing/f1-23-telemetry#2]
I'm using this code to capture the UDP packets.
I have set it up inside a docker container, mapped to 20777 (`EXPOSE 20777/udp` in Dockerfile) and run the `listener.get()` but it just stalls forever, no packet ever gets there.

What could it be?

**Comment by chrishannam** [comment]
Hi, sorry missed this. Does it work outside docker?

**Comment by eliorc** [comment]
Sorry about that, it does work behind Docker now, I assumed that `0.0.0.0` and `localhost` will be interchangeble and they aren't, so it was a mistake on my side, no bug :) I'll close the issue
